version: '3.8'

services:
  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    container_name: minio-local
    
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      
    # 컨테이너의 /data 디렉토리를 호스트의 ./minio-data 디렉토리와 연결하여 데이터를 영구 저장합니다.
    volumes:
      - ./minio-data:/data
      
    ports:
      - "9000:9000" # API 포트
      - "9001:9001" # 콘솔(UI) 포트
      
    # MinIO 서버를 /data 디렉토리를 사용하여 실행하고, 콘솔 주소를 9001로 설정합니다.
    command: server /data --console-address ":9001"
    
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 30s
      timeout: 20s
      retries: 3
      
    networks:
      - minio-net

networks:
  minio-net:
    driver: bridge
