version: "3.8"

services:
  # -------------------- DATABASE --------------------
  rdbms:
    image: mysql:8.0
    container_name: rdbms
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${RDB_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${RDB_DATABASE:-testdb}
      MYSQL_USER: ${RDB_USER:-user}
      MYSQL_PASSWORD: ${RDB_PASSWORD:-pw}
    ports:
      - "${RDB_PORT:-3306}:3306"
    volumes:
      - /data/mysql:/var/lib/mysql

  # -------------------- KAFKA --------------------
  broker:
    container_name: broker
    image: apache/kafka:latest
    ports:
      - "${KAFKA_PORT:-9093}:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXPOSED://0.0.0.0:9093,CONTROLLER://0.0.0.0:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker:9092,EXPOSED://localhost:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXPOSED:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 5
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - /data/kafka:/var/lib/kafka/data
    healthcheck:
      test: nc -z broker 9092 || exit -1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "${KAFKA_UI_PORT:-1234}:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_NAME: local-kafka-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:9092
    depends_on:
      broker:
        condition: service_healthy

  # -------------------- OBJECT STORAGE --------------------
  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    container_name: minio-local
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - /data/minio:/data
    ports:
      - "${MINIO_UI:-9000}:9000" # API 포트
      - "${MMINIO_UI_PORT:-9001}:9001" # 콘솔(UI) 포트
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 30s
      timeout: 20s
      retries: 3
