version: "3.8"

services:
  download:
    image: leedong1848/image-download:latest
    container_name: download
    env_file:
      - ./.env.example
    ports:
      - "8081:8081"
    networks:
      - image-network

  upload:
    image: leedong1848/image-upload:latest

    container_name: upload
    env_file:
      - ./.env.example
    ports:
      - "8080:8080"
    networks:
      - image-network

networks:
  image-network:
    external: true
