topic:
  created: ${CREATED_TOPIC:create-img}
  transcode: ${TRANSCODE_TOPIC:transcode}
spring:
  application:
    name: upload
  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:9093}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

minio:
  url: ${MINIO_URL:http://localhost:9000}
  access-key: ${MINIO_ROOT_USER:minioadmin}
  secret-key: ${MINIO_ROOT_PASSWORD:minioadmin}
  bucket: ${MINIO_BUCKET:image-bucket}

server:
  port: ${UPLOAD_PORT:8080}