name: backend Docker 이미지 빌드 및 푸시

on:
    push:
        branches: ["main"]
        paths:
            - "backend/**"

jobs:
    build_and_push:
        runs-on: ubuntu-latest

        steps:
            - name: 리포지토리 체크아웃
              uses: actions/checkout@v4

            - name: Docker Buildx 설정
              uses: docker/setup-buildx-action@v3

            - name: Docker Hub 로그인
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: transcoding 이미지 빌드 및 푸시
              uses: docker/build-push-action@v5
              with:
                  context: ./backend/transcoding
                  file: ./backend/transcoding/Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/image-transcoding:latest
